# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.12.0.schema.json

PackageIdentifier: co2water.agentegress
PackageVersion: 0.1.2
InstallerType: zip
NestedInstallerType: portable
NestedInstallerFiles:
- RelativeFilePath: agentegress.exe
  PortableCommandAlias: agentegress
ReleaseDate: 2026-09-28
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/co2water/agentegress/releases/download/v0.1.2/agentegress_v0.1.2_windows_amd64.zip
  InstallerSha256: 2DDFED53D7F5456E6644CBEA6B17BFAC3861354CE2221A079654F47F39EA11B4
- Architecture: arm64
  InstallerUrl: https://github.com/co2water/agentegress/releases/download/v0.1.2/agentegress_v0.1.2_windows_arm64.zip
  InstallerSha256: 16CDEA4EDDCD0E8C6B648E64379463C723ECDE5F108C168DD65BDD124EFBD62A
ManifestType: installer
ManifestVersion: 1.12.0
